services:
  server:
    build:
      context: .
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tweety
      MYSQL_USER: roots
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
